FROM node:22-alpine

WORKDIR /app

# Instala wait-for-it para esperar o banco ficar pronto
RUN apk add --no-cache bash

COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./

RUN npm install

COPY . .

EXPOSE 3000 9229

# Usando script de espera + nodemon para hot reload
CMD ["bash", "-c", "while ! nc -z db 3306; do sleep 1; done && rm -rf /app/dist && npm run start:dev"]
